on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

name: MySQLServer
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/jerson/docker-mysql/mysql-server
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: mysql-server/Dockerfile
          context: mysql-server
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: 8.0
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.docker_build.outputs.digest }}
